### ISSUE TITLE
Use biber instead of bibtex for bibliography processing

### ISSUE THREAD

**Issue by dietmarw** [modelica-association/conference-templates#4]
Bibtex with its lack of unicode support and also lack of support of `@online` and `@digital` reference classes is deprecated and the class should rather us Biber in conjunction with biblatex (if must with the natbib compatibility option). 

Any thoughts?

**Comment by akloeckner** [comment]
I just checked with the biblatex documentation, because I do not know the differences too well.

In summary, traditionally the use of bibliography is this:
```latex
\documentclass{...}
\begin{document}
\cite{...}
...
\bibliographystyle{...} % This will be ignored, because
\bibliography{...}      % ...this currently includes \bibliographystyle{plainnat}
\end{document}
```

Biblatex would require this:
```latex
\documentclass{...}              % We load natbib and doi here
\usepackage[style=...]{biblatex} % A user can add this package to their document
\addbibresource{...}             % ... and load resources
\begin{document}                 % This is the same
\cite{...}                       % as is this...
...
\printbibliography               % If no \bibliography is used, this should work
\end{document}
```

According to the biblatex documentation, the default processing of the document also needs to be changed in order for biblatex to work properly (run biber instead of bibtex). I am not sure, many people know how to do this... I myself haven't changed this for my documents yet...

But, actually, nothing should stop an author from just using biblatex, if they wish to. Unless our natbib and doi packages interfer with biblatex...

How about we use the default processing (i.e. bibtex)? But we make sure, we do not load packages imcompatible to biblatex? Authors may then decide to use the traditional toolchain or to switch to biblatex on their own account.

Or, we force authors to switch to biblatex. But we should then be prepared to receive a few questions...

**Comment by dietmarw** [comment]
As far as I know, biber is now shipped with all LaTeX distributions. But you are right not many know about this. Just like many are clear over that the command `latex` is nowadays an alias for `pdflatex` with a post-script option (i.e., a fall back mode really). 

I'm fine with having the example file use `bibtex` and not `biber`. The problem is that the current `modelica.cls` file conflicts with `biblatex` since it loads the conflicting `natbib` package. 
I can think of 2 solutions:
 1. (more elegant): Add an option `backend=bibtex|biber` to the modelica class (just like the biblatex package has) which defaults to `bibtex` for now. This will then load the correct compatible packages and settings.
 2. Remove all bibliography related things from the class file and put this in the `example-paper.tex` instead.

As an example have a look at these [biber & biblatex settings](https://github.com/xogeny/impact/blob/master/resources/docs/modelica2015/paper/impact.tex#L25) to get the same output as natbib.

**Comment by sjoelund** [comment]
There are people who do not use `latexmk`? There are so many commands you need to remember to run if you do things manually that I do not think this is an issue.

**Comment by dietmarw** [comment]
We've just established that the presence of `latexmk` is not guaranteed on LaTeX systems. Though using it is an improvement we should add a check to the Makefile and use fallback option in parallel.

**Comment by dietmarw** [comment]
See above pull-request. Better to have somebody look at it before I force it in.
