### ISSUE TITLE
Bibtex vs Biber

### ISSUE THREAD

**Issue by CSchoel** [modelica-association/conference-templates#9]
The latex template produces quite different outputs when used with biber instead of bibtex. From my point of view it would be desirable to have a more uniform appearance, so that authors have a clear guideline for the citation style.

![biber-bibtex](https://cloud.githubusercontent.com/assets/10725211/21318670/6d3b60b6-c60a-11e6-81bf-db207c811e1f.png)

**Comment by dietmarw** [comment]
Question is, which version should be used. Probably adapt the version that is easier tweakable.

**Comment by bernhard-thiele** [comment]
Of course one could just support one of them.

Biber is often proposed as the more modern and flexible approach of handling citations in latex, and possibly it is easier to adapt it to the bibtex appearance than vice versa. However, I have not much experience with biber since I so far stuck to "old" bibtex.

**Comment by dietmarw** [comment]
The problem with the outdated biber and bibtex is that it is simply lacking current and often used web-based sources.

**Comment by casella** [comment]
If the choice is alternative, please stick to bibtex, which I guess everybody can use. Particularly now that people have already made their submission :)

**Comment by dietmarw** [comment]
Bibtex is exactly the wrong way because then you can not use the normal references you would have nowadays. So I **strongly** suggest to either support biblatex only or biblatex and bibtex. 

I don't see this as something that should be changed for the Modelica2017 conference but can be approached for the next one (when bibtex will be outdated even more as it already is), Biber (and therefore biblatex) has been shipped with all tex distributions for years.

**Comment by casella** [comment]
Fine for me, as long as we start doing this early enough and publicize it widely

**Comment by sjoelund** [comment]
I think Ubuntu 10.04 is the last version of the OS that didn't include biber. It did include biblatex though (it's very old by now). So yes, supporting bibtex should not be necessary.

**Comment by akloeckner** [comment]
My 50 Cent:
- I find the BibTeX output more appealing. It is more compact and does not use overly visible URL formatting.
- The BibLaTeX output seems to be more correct APA style (if we want to use this style, which I would recommend). There is a very good apacite package to make the style even more conformal.
- There should be a very visible note in the example paper, if we change to biblatex/biber. People might be confused, if the document does not compile with their default toolchain (which is de-facto bibtex).

Conclusions:
I would use BibLatex, make it more compact + fully APA conformal and put a big note in the example paper.

**Comment by sjoelund** [comment]
As it is, the bibtex output resembles the sample pdf's for both LaTeX and Word. So yes, I assume that if biblatex is used, a different style should be used.

**Comment by sjoelund** [comment]
Seems to just need `\DeclareNameAlias{sortname}{given-family}` to make it output a style more similar to the bibtex (still with formatting on the URL though)

**Comment by dietmarw** [comment]
Great. That solves already the main difference.

**Comment by dietmarw** [comment]
But then again I find it more difficult to find the reference in the listing when it is sorted by family-name but displayed by first name first. So the biblatex version is the one which I would prefer.

**Comment by sjoelund** [comment]
#18 uses \small for the bibliography and skips texttt for URLs in it. I agree that the reference style is nicer: it's easier to find an author in the list when you don't have to parse for the second name in the list, so I kept that.

There are additional changes, unrelated, changed too.
